# Generated by Django 2.2 on 2019-05-12 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlct_ca_nhan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qlct_nhom', '0003_nhom_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hoa_don', models.CharField(blank=True, max_length=45, null=True)),
                ('so_tien', models.IntegerField(blank=True, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=500, null=True)),
                ('thoi_gian_giao_dich', models.DateTimeField(blank=True, null=True)),
                ('linh_vuc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qlct_ca_nhan.LinhVuc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vi_ca_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qlct_ca_nhan.ViCaNhan')),
                ('vi_nhom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qlct_nhom.ViNhom')),
            ],
            options={
                'db_table': 'hoa_don',
            },
        ),
    ]
