# Generated by Django 2.2 on 2019-05-11 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='Test', max_length=50)),
                ('dinh_muc', models.IntegerField()),
            ],
            options={
                'db_table': 'nhom',
            },
        ),
        migrations.CreateModel(
            name='ViNhom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, max_length=45, null=True)),
                ('dinh_muc', models.IntegerField(blank=True, null=True)),
                ('so_du', models.IntegerField(blank=True, null=True)),
                ('auth_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlct_nhom.Nhom')),
            ],
            options={
                'db_table': 'vi_nhom',
            },
        ),
        migrations.CreateModel(
            name='NhomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinh_muc', models.IntegerField(null=True)),
                ('is_leader', models.IntegerField(default=0)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlct_nhom.Nhom')),
            ],
            options={
                'db_table': 'nhom_user',
                'unique_together': {('auth_user', 'nhom')},
            },
        ),
    ]
