# Generated by Django 2.2 on 2019-05-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlct_nhom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhom',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nhomuser',
            name='nhom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qlct_nhom.Nhom'),
        ),
    ]
