# Generated by Django 2.2 on 2019-05-11 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qlct_nhom', '0002_auto_20190511_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhom',
            name='users',
            field=models.ManyToManyField(through='qlct_nhom.NhomUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
