# Generated by Django 2.2 on 2019-05-12 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_so_no', models.CharField(blank=True, max_length=200, null=True)),
                ('so_tien', models.IntegerField(blank=True, null=True)),
                ('doi_tac', models.CharField(blank=True, max_length=200, null=True)),
                ('loai', models.IntegerField(blank=True, null=True)),
                ('ngay_vay', models.DateTimeField(blank=True, null=True)),
                ('ngay_tra', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sono', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'so_no',
            },
        ),
    ]
