# Generated by Django 2.2 on 2019-05-09 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViCaNhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, max_length=45, null=True)),
                ('dinh_muc', models.IntegerField(blank=True, null=True)),
                ('so_du', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vi_ca_nhan',
            },
        ),
        migrations.CreateModel(
            name='LinhVuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, max_length=45, null=True)),
                ('loai', models.IntegerField(blank=True, null=True)),
                ('auth_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('linh_vuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qlct_ca_nhan.LinhVuc')),
            ],
            options={
                'db_table': 'linh_vuc',
            },
        ),
    ]
